AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  NonProdAccount:
    Description: AWS AccountNumber for the Non Prod Account
    Type: Number

Resources:
  ListBookingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-bookings-lambda.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          BOOKING_TABLE_NAME: !Ref BookingsDBTable
      Events:
        GetBookings:
          Type: Api
          Properties:
            Path: /bookings
            Method: get

  PostBookingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: post-bookings-lambda.handler
      Runtime: nodejs4.3
      Policies:
         - AmazonDynamoDBFullAccess
         - AmazonSNSFullAccess
      Environment:
        Variables:
          BOOKING_SNS_ARN: !Ref BookingTopic
          BOOKING_TABLE_NAME: !Ref BookingsDBTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /bookings
            Method: post

  BookingTopic:
     Type: "AWS::SNS::Topic"

  BookingTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: BookingTopicPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: BookingTopicPolicy-stmt1
          Effect: Allow
          Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
          Action:
            - sns:Publish
            - sns:RemovePermission
            - sns:SetTopicAttributes
            - sns:DeleteTopic
            - sns:ListSubscriptionsByTopic
            - sns:GetTopicAttributes
            - sns:Receive
            - sns:AddPermission
            - sns:Subscribe
          Resource: !Ref BookingTopic
        - Sid: BookingTopicPolicy-stmt2
          Effect: Allow
          Principal:
              AWS:
                - !Sub arn:aws:iam::${NonProdAccount}:root
          Action:
            - sns:Publish
            - sns:Subscribe
            - sns:ListSubscriptionsByTopic
          Resource: !Ref BookingTopic
      Topics:
      - !Ref BookingTopic

  BookingsDBTable:
     Type: AWS::DynamoDB::Table
     Properties:
      AttributeDefinitions:
        -
          AttributeName: "bookingid"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "bookingid"
          KeyType: HASH
      ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5

Outputs:
    BookingAPI:
        Description: Booking API Endpoint
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com'
        Export:
            Name: !Sub '${AWS::StackName}-BookingAPI'
    BookingTopicArn:
        Description: Booking Topic Arn
        Value: !Ref BookingTopic
        Export:
            Name: !Sub '${AWS::StackName}-BookingTopicArn'